/**
 * Comprehensive Role, Skills, and Location Constants
 * Recruiter-grade taxonomy for job matching
 */

// Job roles - comprehensive taxonomy covering tech and non-tech
export const JOB_ROLES = {
  // Technology Roles
  "Engineering - Frontend": [
    "Frontend Developer",
    "React Developer",
    "Angular Developer",
    "Vue.js Developer",
    "UI Developer",
    "Web Developer",
  ],
  "Engineering - Backend": [
    "Backend Developer",
    "Node.js Developer",
    "Java Developer",
    "Python Developer",
    "Go Developer",
    ".NET Developer",
    "PHP Developer",
  ],
  "Engineering - Full Stack": [
    "Full Stack Developer",
    "Software Engineer",
    "Software Development Engineer",
    "MERN Stack Developer",
    "MEAN Stack Developer",
  ],
  "Engineering - Mobile": [
    "Mobile Developer",
    "iOS Developer",
    "Android Developer",
    "React Native Developer",
    "Flutter Developer",
  ],
  "Engineering - DevOps & Cloud": [
    "DevOps Engineer",
    "Site Reliability Engineer",
    "Cloud Engineer",
    "Platform Engineer",
    "Infrastructure Engineer",
    "Kubernetes Engineer",
  ],
  "Engineering - QA & Testing": [
    "QA Engineer",
    "Test Engineer",
    "Automation Engineer",
    "SDET",
    "Quality Assurance Lead",
    "Performance Test Engineer",
  ],
  "Engineering - Security": [
    "Security Engineer",
    "Application Security Engineer",
    "Cloud Security Engineer",
    "Penetration Tester",
    "SOC Analyst",
    "Cybersecurity Analyst",
  ],
  "Data & Analytics": [
    "Data Analyst",
    "Business Analyst",
    "Data Scientist",
    "Data Engineer",
    "Machine Learning Engineer",
    "AI/ML Engineer",
    "Business Intelligence Analyst",
    "Analytics Manager",
  ],
  "Design": [
    "UX Designer",
    "UI Designer",
    "Product Designer",
    "UX Researcher",
    "Visual Designer",
    "Interaction Designer",
    "Design Lead",
  ],
  // Non-Technology Roles
  "Product & Project Management": [
    "Product Manager",
    "Associate Product Manager",
    "Senior Product Manager",
    "Technical Product Manager",
    "Project Manager",
    "Program Manager",
    "Scrum Master",
    "Agile Coach",
  ],
  "Sales": [
    "Sales Executive",
    "Sales Manager",
    "Account Executive",
    "Business Development Representative",
    "Sales Development Representative",
    "Inside Sales Representative",
    "Enterprise Sales Manager",
    "Key Account Manager",
    "Regional Sales Manager",
  ],
  "Business Development": [
    "Business Development Executive",
    "Business Development Manager",
    "Partnerships Manager",
    "Strategic Partnerships Lead",
    "Alliance Manager",
  ],
  "Marketing": [
    "Marketing Manager",
    "Digital Marketing Manager",
    "Performance Marketing Manager",
    "Growth Marketing Manager",
    "Content Marketing Manager",
    "SEO Specialist",
    "Social Media Manager",
    "Brand Manager",
    "Marketing Analyst",
  ],
  "Human Resources": [
    "HR Manager",
    "HR Business Partner",
    "HR Generalist",
    "Recruiter",
    "Technical Recruiter",
    "Talent Acquisition Specialist",
    "Talent Acquisition Lead",
    "People Operations Manager",
    "Compensation & Benefits Manager",
  ],
  "Customer Success & Support": [
    "Customer Success Manager",
    "Customer Support Executive",
    "Technical Support Engineer",
    "Customer Experience Manager",
    "Implementation Specialist",
    "Client Relationship Manager",
    "Support Team Lead",
  ],
  "Operations & Strategy": [
    "Operations Manager",
    "Operations Analyst",
    "Strategy Manager",
    "Business Operations Manager",
    "Chief of Staff",
    "Management Consultant",
  ],
  "Finance & Accounting": [
    "Financial Analyst",
    "Finance Manager",
    "Accountant",
    "Senior Accountant",
    "FP&A Analyst",
    "Controller",
    "Audit Manager",
  ],
};

// Flatten for dropdown with categories
export const ALL_ROLES = Object.entries(JOB_ROLES).flatMap(([category, roles]) =>
  roles.map(role => ({ value: role, label: role, category }))
);

// ============================================================================
// SKILLS DATABASE - 300+ skills across categories
// ============================================================================

export const SKILLS = {
  // Programming Languages
  "Programming Languages": [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C++",
    "C#",
    "Go",
    "Rust",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "Scala",
    "R",
    "MATLAB",
    "Perl",
    "Shell Scripting",
    "Bash",
    "PowerShell",
    "SQL",
    "PL/SQL",
    "Groovy",
    "Dart",
    "Lua",
    "Objective-C",
    "COBOL",
    "Fortran",
    "Assembly",
    "Haskell",
    "Elixir",
    "Clojure",
  ],

  // Frontend Technologies
  "Frontend Development": [
    "React",
    "Angular",
    "Vue.js",
    "Next.js",
    "Nuxt.js",
    "Svelte",
    "jQuery",
    "HTML5",
    "CSS3",
    "SASS/SCSS",
    "Less",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Chakra UI",
    "Styled Components",
    "Redux",
    "MobX",
    "Zustand",
    "React Query",
    "GraphQL Client",
    "Webpack",
    "Vite",
    "Babel",
    "ESLint",
    "Jest",
    "Cypress",
    "Playwright",
    "Storybook",
    "Responsive Design",
    "Web Accessibility (WCAG)",
    "PWA Development",
  ],

  // Backend Technologies
  "Backend Development": [
    "Node.js",
    "Express.js",
    "NestJS",
    "Django",
    "Flask",
    "FastAPI",
    "Spring Boot",
    "Spring Framework",
    "Hibernate",
    "ASP.NET Core",
    ".NET Framework",
    "Ruby on Rails",
    "Laravel",
    "Symfony",
    "CodeIgniter",
    "Gin",
    "Echo",
    "Fiber",
    "Actix",
    "Phoenix",
    "REST APIs",
    "GraphQL",
    "gRPC",
    "WebSockets",
    "Message Queues",
    "Microservices",
    "Event-Driven Architecture",
    "CQRS",
    "Domain-Driven Design",
  ],

  // Databases
  "Databases": [
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "Oracle Database",
    "Microsoft SQL Server",
    "SQLite",
    "Cassandra",
    "DynamoDB",
    "Firebase",
    "Supabase",
    "Neo4j",
    "CouchDB",
    "InfluxDB",
    "TimescaleDB",
    "MariaDB",
    "Memcached",
    "Apache HBase",
    "Amazon RDS",
    "Database Design",
    "Query Optimization",
    "Database Administration",
  ],

  // Cloud & DevOps
  "Cloud & DevOps": [
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI/CD",
    "CircleCI",
    "ArgoCD",
    "Helm",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "Datadog",
    "New Relic",
    "Splunk",
    "AWS Lambda",
    "Azure Functions",
    "CloudFormation",
    "Pulumi",
    "Nginx",
    "Apache",
    "HAProxy",
    "Load Balancing",
    "CDN (Cloudflare/Akamai)",
    "Linux Administration",
    "Shell Scripting",
    "Infrastructure as Code",
    "Site Reliability Engineering",
    "Monitoring & Alerting",
  ],

  // Mobile Development
  "Mobile Development": [
    "React Native",
    "Flutter",
    "iOS Development",
    "Android Development",
    "SwiftUI",
    "Jetpack Compose",
    "Xamarin",
    "Ionic",
    "Capacitor",
    "Cordova",
    "Mobile UI/UX",
    "App Store Optimization",
    "Push Notifications",
    "Mobile Analytics",
    "Firebase (Mobile)",
    "CoreData",
    "Room Database",
  ],

  // Data & AI/ML
  "Data & AI/ML": [
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "Apache Spark",
    "Apache Kafka",
    "Apache Airflow",
    "Databricks",
    "Snowflake",
    "Data Warehousing",
    "ETL Pipelines",
    "Data Modeling",
    "Feature Engineering",
    "A/B Testing",
    "Statistical Analysis",
    "Predictive Modeling",
    "Recommendation Systems",
    "LLMs & Prompt Engineering",
    "MLOps",
    "OpenAI API",
    "Hugging Face",
    "Langchain",
    "RAG (Retrieval Augmented Generation)",
  ],

  // Testing & QA
  "Testing & Quality Assurance": [
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Performance Testing",
    "Load Testing",
    "Security Testing",
    "API Testing",
    "Selenium",
    "Appium",
    "JMeter",
    "Locust",
    "Postman",
    "SoapUI",
    "TestNG",
    "JUnit",
    "PyTest",
    "Mocha",
    "Chai",
    "Test Automation",
    "BDD/TDD",
    "Cucumber",
    "Robot Framework",
  ],

  // Security
  "Security": [
    "Application Security",
    "Cloud Security",
    "Network Security",
    "OWASP Top 10",
    "Penetration Testing",
    "Vulnerability Assessment",
    "SIEM",
    "SOC Operations",
    "Identity & Access Management",
    "OAuth/OIDC",
    "JWT",
    "SSL/TLS",
    "Encryption",
    "Compliance (SOC2, GDPR, HIPAA)",
    "Security Auditing",
    "Threat Modeling",
    "Incident Response",
  ],

  // Project & Product Management
  "Project & Product Management": [
    "Agile Methodology",
    "Scrum",
    "Kanban",
    "Jira",
    "Confluence",
    "Asana",
    "Trello",
    "Monday.com",
    "Product Roadmapping",
    "User Story Writing",
    "Sprint Planning",
    "Stakeholder Management",
    "Requirements Gathering",
    "Product Analytics",
    "Mixpanel",
    "Amplitude",
    "Google Analytics",
    "A/B Testing",
    "User Research",
    "Market Research",
    "Competitive Analysis",
    "Go-to-Market Strategy",
    "OKRs",
    "KPIs",
    "Lean Methodology",
    "Six Sigma",
    "PMP",
    "Prince2",
  ],

  // Design & UX
  "Design & UX": [
    "Figma",
    "Adobe XD",
    "Sketch",
    "InVision",
    "Zeplin",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe After Effects",
    "UI Design",
    "UX Design",
    "Wireframing",
    "Prototyping",
    "User Research",
    "Usability Testing",
    "Design Systems",
    "Interaction Design",
    "Visual Design",
    "Information Architecture",
    "Design Thinking",
    "Accessibility Design",
  ],

  // Sales & Business Development
  "Sales & Business Development": [
    "Sales Strategy",
    "Lead Generation",
    "Cold Calling",
    "Cold Emailing",
    "Sales Presentations",
    "Negotiation",
    "Account Management",
    "CRM (Salesforce)",
    "CRM (HubSpot)",
    "CRM (Zoho)",
    "Sales Pipeline Management",
    "Sales Forecasting",
    "Enterprise Sales",
    "SaaS Sales",
    "Solution Selling",
    "Consultative Selling",
    "Partnership Development",
    "Contract Negotiation",
    "Revenue Operations",
    "Sales Enablement",
  ],

  // Marketing
  "Marketing": [
    "Digital Marketing",
    "Content Marketing",
    "SEO",
    "SEM/PPC",
    "Google Ads",
    "Meta Ads",
    "LinkedIn Ads",
    "Email Marketing",
    "Marketing Automation",
    "HubSpot",
    "Mailchimp",
    "Marketo",
    "Social Media Marketing",
    "Influencer Marketing",
    "Brand Strategy",
    "Marketing Analytics",
    "Content Strategy",
    "Copywriting",
    "Video Marketing",
    "Podcast Production",
    "PR & Communications",
    "Event Marketing",
    "Growth Hacking",
    "Conversion Rate Optimization",
    "Landing Page Optimization",
  ],

  // Human Resources
  "Human Resources": [
    "Talent Acquisition",
    "Technical Recruiting",
    "Sourcing",
    "LinkedIn Recruiter",
    "ATS (Greenhouse/Lever)",
    "Interview Coordination",
    "Employer Branding",
    "Employee Engagement",
    "Performance Management",
    "Compensation & Benefits",
    "HRIS Systems",
    "Workday",
    "BambooHR",
    "Payroll Management",
    "Labor Law",
    "Diversity & Inclusion",
    "Training & Development",
    "Organizational Development",
    "Change Management",
    "Employee Relations",
  ],

  // Finance & Accounting
  "Finance & Accounting": [
    "Financial Analysis",
    "Financial Modeling",
    "FP&A",
    "Budgeting",
    "Forecasting",
    "Variance Analysis",
    "Financial Reporting",
    "GAAP",
    "IFRS",
    "Accounts Payable",
    "Accounts Receivable",
    "General Ledger",
    "Cost Accounting",
    "Tax Planning",
    "Audit",
    "Risk Management",
    "Treasury Management",
    "Investment Analysis",
    "Excel (Advanced)",
    "Power BI",
    "Tableau",
    "SAP",
    "Oracle Financials",
    "QuickBooks",
    "NetSuite",
  ],

  // Operations
  "Operations": [
    "Process Improvement",
    "Operations Management",
    "Supply Chain Management",
    "Logistics",
    "Inventory Management",
    "Vendor Management",
    "Procurement",
    "Quality Management",
    "ISO Standards",
    "Lean Operations",
    "Six Sigma",
    "Business Process Mapping",
    "Workflow Automation",
    "Capacity Planning",
    "Resource Allocation",
  ],

  // Communication & Soft Skills
  "Communication & Soft Skills": [
    "Communication",
    "Presentation Skills",
    "Public Speaking",
    "Technical Writing",
    "Documentation",
    "Stakeholder Communication",
    "Cross-functional Collaboration",
    "Team Leadership",
    "Mentoring",
    "Conflict Resolution",
    "Problem Solving",
    "Critical Thinking",
    "Decision Making",
    "Time Management",
    "Adaptability",
    "Remote Collaboration",
    "Client Management",
  ],

  // Tools & Productivity
  "Tools & Productivity": [
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "VS Code",
    "IntelliJ IDEA",
    "Slack",
    "Microsoft Teams",
    "Zoom",
    "Notion",
    "Obsidian",
    "Microsoft Office Suite",
    "Google Workspace",
    "Miro",
    "Lucidchart",
    "Draw.io",
  ],

  // Domain Expertise
  "Domain Expertise": [
    "E-commerce",
    "FinTech",
    "HealthTech",
    "EdTech",
    "SaaS",
    "B2B",
    "B2C",
    "Enterprise Software",
    "Payments & Billing",
    "Banking & Insurance",
    "Retail",
    "Logistics & Supply Chain",
    "Real Estate",
    "Travel & Hospitality",
    "Gaming",
    "Media & Entertainment",
    "Advertising & AdTech",
    "Telecommunications",
    "Manufacturing",
    "Automotive",
    "Energy & Utilities",
    "Government & Public Sector",
    "Non-profit",
  ],
};

// Flatten skills for search
export const ALL_SKILLS = Object.entries(SKILLS).flatMap(([category, skills]) =>
  skills.map(skill => ({ value: skill, label: skill, category }))
);

// Get skills count
export const SKILLS_COUNT = ALL_SKILLS.length;

// Locations - India (States + Major Cities) and Global
export const LOCATIONS = {
  "India - Metro Cities": [
    "Bangalore",
    "Mumbai",
    "Delhi NCR",
    "Hyderabad",
    "Chennai",
    "Pune",
    "Kolkata",
    "Ahmedabad",
    "Noida",
    "Gurugram",
  ],
  "India - Tier 2 Cities": [
    "Jaipur",
    "Lucknow",
    "Chandigarh",
    "Indore",
    "Bhopal",
    "Kochi",
    "Coimbatore",
    "Nagpur",
    "Vadodara",
    "Surat",
    "Mysore",
    "Trivandrum",
    "Vizag",
  ],
  "India - States": [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Delhi",
    "Jammu & Kashmir",
    "Ladakh",
  ],
  "Global - North America": [
    "United States",
    "USA - California",
    "USA - New York",
    "USA - Texas",
    "USA - Washington",
    "USA - Massachusetts",
    "Canada",
    "Canada - Ontario",
    "Canada - British Columbia",
  ],
  "Global - Europe": [
    "United Kingdom",
    "UK - London",
    "Germany",
    "Germany - Berlin",
    "Germany - Munich",
    "Netherlands",
    "Ireland",
    "France",
    "Switzerland",
    "Sweden",
    "Poland",
  ],
  "Global - Middle East": [
    "United Arab Emirates",
    "UAE - Dubai",
    "UAE - Abu Dhabi",
    "Saudi Arabia",
    "Qatar",
    "Bahrain",
    "Kuwait",
    "Oman",
  ],
  "Global - Asia Pacific": [
    "Singapore",
    "Australia",
    "Australia - Sydney",
    "Australia - Melbourne",
    "Japan",
    "Hong Kong",
    "Malaysia",
    "Indonesia",
    "Philippines",
    "Vietnam",
    "Thailand",
  ],
  "Remote": [
    "Remote - India Only",
    "Remote - Global",
    "Remote - US Timezone",
    "Remote - EU Timezone",
    "Remote - APAC Timezone",
    "Hybrid - Flexible",
  ],
};

// Flatten for dropdown with regions
export const ALL_LOCATIONS = Object.entries(LOCATIONS).flatMap(([region, locations]) =>
  locations.map(loc => ({ value: loc, label: loc, region }))
);

// Experience years options (0-40)
export const EXPERIENCE_YEARS = [
  { value: "0", label: "Fresher (0 years)" },
  { value: "1", label: "1 year" },
  { value: "2", label: "2 years" },
  { value: "3", label: "3 years" },
  { value: "4", label: "4 years" },
  { value: "5", label: "5 years" },
  { value: "6", label: "6 years" },
  { value: "7", label: "7 years" },
  { value: "8", label: "8 years" },
  { value: "9", label: "9 years" },
  { value: "10", label: "10 years" },
  { value: "11", label: "11 years" },
  { value: "12", label: "12 years" },
  { value: "13", label: "13 years" },
  { value: "14", label: "14 years" },
  { value: "15", label: "15 years" },
  { value: "16", label: "16 years" },
  { value: "17", label: "17 years" },
  { value: "18", label: "18 years" },
  { value: "19", label: "19 years" },
  { value: "20", label: "20 years" },
  { value: "21", label: "21-25 years" },
  { value: "26", label: "26-30 years" },
  { value: "31", label: "31-35 years" },
  { value: "36", label: "36-40 years" },
];

// Experience months options
export const EXPERIENCE_MONTHS = [
  { value: "0", label: "0 months" },
  { value: "1", label: "1 month" },
  { value: "2", label: "2 months" },
  { value: "3", label: "3 months" },
  { value: "4", label: "4 months" },
  { value: "5", label: "5 months" },
  { value: "6", label: "6 months" },
  { value: "7", label: "7 months" },
  { value: "8", label: "8 months" },
  { value: "9", label: "9 months" },
  { value: "10", label: "10 months" },
  { value: "11", label: "11 months" },
];

// Max roles allowed
export const MAX_ROLES = 3;

// Max skills before warning
export const MAX_SKILLS_WARNING = 20;
