/**
 * Comprehensive Role, Skills, and Location Constants
 * Production-grade taxonomy for job matching
 * 500+ roles, 700+ skills covering tech and non-tech domains
 */

// ============================================================================
// JOB ROLES DATABASE - 500+ roles across tech and non-tech
// ============================================================================

export const JOB_ROLES = {
  // ========================
  // TECHNOLOGY ROLES
  // ========================
  "Engineering - Frontend": [
    "Frontend Developer",
    "React Developer",
    "Angular Developer",
    "Vue.js Developer",
    "UI Developer",
    "Web Developer",
    "Senior Frontend Developer",
    "Lead Frontend Developer",
    "Principal Frontend Engineer",
    "Frontend Architect",
  ],
  "Engineering - Backend": [
    "Backend Developer",
    "Node.js Developer",
    "Java Developer",
    "Python Developer",
    "Go Developer",
    ".NET Developer",
    "PHP Developer",
    "Ruby Developer",
    "Senior Backend Developer",
    "Lead Backend Developer",
    "Principal Backend Engineer",
    "Backend Architect",
  ],
  "Engineering - Full Stack": [
    "Full Stack Developer",
    "Software Engineer",
    "Software Development Engineer",
    "MERN Stack Developer",
    "MEAN Stack Developer",
    "Senior Software Engineer",
    "Staff Software Engineer",
    "Principal Software Engineer",
    "Engineering Manager",
    "Director of Engineering",
    "VP of Engineering",
    "CTO",
  ],
  "Engineering - Mobile": [
    "Mobile Developer",
    "iOS Developer",
    "Android Developer",
    "React Native Developer",
    "Flutter Developer",
    "Senior Mobile Developer",
    "Lead Mobile Developer",
    "Mobile Architect",
  ],
  "Engineering - DevOps & Cloud": [
    "DevOps Engineer",
    "Site Reliability Engineer",
    "Cloud Engineer",
    "Platform Engineer",
    "Infrastructure Engineer",
    "Kubernetes Engineer",
    "AWS Solutions Architect",
    "Azure Cloud Engineer",
    "GCP Engineer",
    "Senior DevOps Engineer",
    "Lead DevOps Engineer",
    "DevOps Manager",
    "Cloud Architect",
    "Head of Infrastructure",
  ],
  "Engineering - QA & Testing": [
    "QA Engineer",
    "Test Engineer",
    "Automation Engineer",
    "SDET",
    "Quality Assurance Lead",
    "Performance Test Engineer",
    "Senior QA Engineer",
    "QA Manager",
    "QA Director",
    "Test Architect",
  ],
  "Engineering - Security": [
    "Security Engineer",
    "Application Security Engineer",
    "Cloud Security Engineer",
    "Penetration Tester",
    "SOC Analyst",
    "Cybersecurity Analyst",
    "Security Architect",
    "CISO",
    "Security Manager",
    "InfoSec Manager",
  ],
  "Engineering - Insurance & Enterprise": [
    "Guidewire Developer",
    "Guidewire Consultant",
    "Guidewire PolicyCenter Developer",
    "Guidewire ClaimCenter Developer",
    "Guidewire BillingCenter Developer",
    "Guidewire Architect",
    "Senior Guidewire Developer",
    "Lead Guidewire Developer",
    "Insurance Software Developer",
    "Duck Creek Developer",
    "SAP Developer",
    "SAP ABAP Developer",
    "SAP Consultant",
    "SAP Functional Consultant",
    "SAP Technical Consultant",
    "Oracle Developer",
    "Oracle DBA",
    "Salesforce Developer",
    "Salesforce Administrator",
    "Salesforce Consultant",
    "ServiceNow Developer",
    "ServiceNow Administrator",
    "Workday Consultant",
    "ERP Consultant",
    "ERP Developer",
  ],
  "Data & Analytics": [
    "Data Analyst",
    "Business Analyst",
    "Data Scientist",
    "Data Engineer",
    "Machine Learning Engineer",
    "AI/ML Engineer",
    "Business Intelligence Analyst",
    "Analytics Manager",
    "Senior Data Scientist",
    "Lead Data Engineer",
    "Head of Data",
    "Chief Data Officer",
    "Data Architect",
    "BI Developer",
    "ETL Developer",
    "Big Data Engineer",
    "NLP Engineer",
    "Computer Vision Engineer",
    "AI Research Scientist",
  ],
  "Design": [
    "UX Designer",
    "UI Designer",
    "Product Designer",
    "UX Researcher",
    "Visual Designer",
    "Interaction Designer",
    "Design Lead",
    "Senior Product Designer",
    "Design Manager",
    "Head of Design",
    "Creative Director",
    "Brand Designer",
    "Graphic Designer",
    "Motion Designer",
  ],

  // ========================
  // EXECUTIVE & C-SUITE ROLES
  // ========================
  "Executive Leadership": [
    "Chief Executive Officer (CEO)",
    "Chief Operating Officer (COO)",
    "Chief Financial Officer (CFO)",
    "Chief Marketing Officer (CMO)",
    "Chief Technology Officer (CTO)",
    "Chief People Officer (CPO)",
    "Chief Revenue Officer (CRO)",
    "Chief Strategy Officer (CSO)",
    "Chief Product Officer",
    "Chief Customer Officer (CCO)",
    "Chief Legal Officer (CLO)",
    "Chief Compliance Officer",
    "Chief Digital Officer (CDO)",
    "Chief Information Officer (CIO)",
    "Chief Human Resources Officer (CHRO)",
    "Chief Administrative Officer (CAO)",
    "Chief Commercial Officer",
    "Chief Risk Officer",
    "Managing Director",
    "President",
    "Vice Chairman",
    "Chairman",
    "Executive Director",
    "Board Member",
    "Partner",
    "Senior Partner",
    "Managing Partner",
    "Founder",
    "Co-Founder",
  ],

  // ========================
  // SENIOR LEADERSHIP & VP ROLES
  // ========================
  "Senior Leadership": [
    "Vice President - Sales",
    "Vice President - Marketing",
    "Vice President - Operations",
    "Vice President - Finance",
    "Vice President - HR",
    "Vice President - Business Development",
    "Vice President - Strategy",
    "Vice President - Product",
    "Vice President - Customer Success",
    "Vice President - Engineering",
    "Associate Vice President (AVP)",
    "AVP - Sales",
    "AVP - Operations",
    "AVP - Marketing",
    "AVP - Finance",
    "AVP - HR",
    "Senior Vice President (SVP)",
    "SVP - Sales",
    "SVP - Operations",
    "SVP - Strategy",
    "Executive Vice President (EVP)",
    "Group Vice President",
    "Division Head",
    "Business Unit Head",
    "General Manager",
    "Country Manager",
    "Regional Director",
    "Regional Head",
    "Zone Head",
    "Cluster Head",
  ],

  // ========================
  // PRODUCT & PROJECT MANAGEMENT
  // ========================
  "Product Management": [
    "Product Manager",
    "Associate Product Manager",
    "Senior Product Manager",
    "Principal Product Manager",
    "Group Product Manager",
    "Director of Product",
    "VP of Product",
    "Head of Product",
    "Technical Product Manager",
    "Platform Product Manager",
    "Growth Product Manager",
    "Product Owner",
    "Product Analyst",
    "Product Strategist",
    "Product Marketing Manager",
    "Product Operations Manager",
  ],
  "Program & Project Management": [
    "Project Manager",
    "Senior Project Manager",
    "Program Manager",
    "Senior Program Manager",
    "Principal Program Manager",
    "Director of Program Management",
    "PMO Director",
    "PMO Manager",
    "Delivery Manager",
    "Senior Delivery Manager",
    "Engagement Manager",
    "Portfolio Manager",
    "Scrum Master",
    "Agile Coach",
    "Release Manager",
    "Change Manager",
    "Implementation Manager",
    "Technical Project Manager",
    "IT Project Manager",
    "ERP Project Manager",
    "Construction Project Manager",
  ],

  // ========================
  // SALES ROLES (Comprehensive)
  // ========================
  "Sales - Executive Level": [
    "Sales Executive",
    "Senior Sales Executive",
    "Sales Consultant",
    "Sales Specialist",
    "Field Sales Executive",
    "Inside Sales Executive",
    "Outside Sales Executive",
    "Territory Sales Executive",
  ],
  "Sales - Management": [
    "Sales Manager",
    "Senior Sales Manager",
    "Area Sales Manager",
    "Regional Sales Manager",
    "Zonal Sales Manager",
    "National Sales Manager",
    "International Sales Manager",
    "Sales Team Lead",
    "Assistant Sales Manager",
    "Deputy Sales Manager",
    "Sales Supervisor",
  ],
  "Sales - Account Management": [
    "Account Manager",
    "Key Account Manager",
    "Senior Account Manager",
    "Strategic Account Manager",
    "Global Account Manager",
    "Enterprise Account Manager",
    "Named Account Manager",
    "Account Director",
    "Client Partner",
    "Client Relationship Manager",
    "Customer Relationship Manager",
  ],
  "Sales - Business Development": [
    "Business Development Executive",
    "Business Development Manager",
    "Senior Business Development Manager",
    "Business Development Lead",
    "Business Development Director",
    "Business Development Representative (BDR)",
    "Sales Development Representative (SDR)",
    "Lead Development Representative",
    "Market Development Manager",
    "Partnership Manager",
    "Partnerships Lead",
    "Alliance Manager",
    "Strategic Alliances Manager",
    "Channel Manager",
    "Channel Sales Manager",
    "Channel Partner Manager",
    "Distribution Manager",
    "Reseller Manager",
  ],
  "Sales - Specialized": [
    "Enterprise Sales Manager",
    "Enterprise Account Executive",
    "Mid-Market Sales Manager",
    "SMB Sales Manager",
    "Corporate Sales Manager",
    "Government Sales Manager",
    "Public Sector Sales Manager",
    "Healthcare Sales Manager",
    "Pharmaceutical Sales Representative",
    "Medical Device Sales Representative",
    "Real Estate Sales Agent",
    "Insurance Sales Agent",
    "Financial Advisor",
    "Investment Advisor",
    "Wealth Advisor",
    "Mortgage Advisor",
    "Loan Officer",
    "Pre-Sales Consultant",
    "Solutions Consultant",
    "Technical Sales Engineer",
    "Sales Engineer",
    "Demo Engineer",
    "Revenue Operations Manager",
    "Sales Operations Manager",
    "Sales Enablement Manager",
    "Sales Training Manager",
    "Bid Manager",
    "Proposal Manager",
    "RFP Manager",
    "Tender Manager",
  ],

  // ========================
  // MARKETING ROLES (Comprehensive)
  // ========================
  "Marketing - Management": [
    "Marketing Manager",
    "Senior Marketing Manager",
    "Marketing Director",
    "Head of Marketing",
    "VP of Marketing",
    "CMO",
    "Marketing Lead",
    "Marketing Team Lead",
    "Assistant Marketing Manager",
  ],
  "Marketing - Digital & Performance": [
    "Digital Marketing Manager",
    "Digital Marketing Specialist",
    "Performance Marketing Manager",
    "Performance Marketing Specialist",
    "Paid Media Manager",
    "Paid Media Specialist",
    "PPC Specialist",
    "SEM Specialist",
    "Google Ads Specialist",
    "Meta Ads Specialist",
    "LinkedIn Ads Specialist",
    "Programmatic Advertising Manager",
    "Display Advertising Manager",
    "Affiliate Marketing Manager",
    "Affiliate Manager",
    "Mobile Marketing Manager",
    "App Marketing Manager",
  ],
  "Marketing - Growth & Product": [
    "Growth Marketing Manager",
    "Growth Manager",
    "Growth Lead",
    "Head of Growth",
    "VP of Growth",
    "Growth Hacker",
    "User Acquisition Manager",
    "Retention Marketing Manager",
    "Lifecycle Marketing Manager",
    "CRM Marketing Manager",
    "Marketing Automation Specialist",
    "Conversion Rate Optimization Specialist",
    "Landing Page Specialist",
    "Funnel Specialist",
  ],
  "Marketing - Content & SEO": [
    "Content Marketing Manager",
    "Content Marketing Specialist",
    "Content Strategist",
    "Content Lead",
    "Head of Content",
    "SEO Manager",
    "SEO Specialist",
    "SEO Analyst",
    "Technical SEO Specialist",
    "Link Building Specialist",
    "Content Writer",
    "Copywriter",
    "Senior Copywriter",
    "Creative Copywriter",
    "Technical Writer",
    "UX Writer",
    "Blog Manager",
    "Editorial Manager",
    "Editor-in-Chief",
  ],
  "Marketing - Brand & Communications": [
    "Brand Manager",
    "Senior Brand Manager",
    "Brand Director",
    "Brand Strategist",
    "Communications Manager",
    "Corporate Communications Manager",
    "Internal Communications Manager",
    "PR Manager",
    "Public Relations Specialist",
    "Media Relations Manager",
    "Press Officer",
    "Spokesperson",
    "Social Media Manager",
    "Social Media Specialist",
    "Community Manager",
    "Influencer Marketing Manager",
    "Employer Branding Manager",
    "Reputation Manager",
  ],
  "Marketing - Events & Field": [
    "Event Marketing Manager",
    "Events Manager",
    "Event Coordinator",
    "Trade Show Manager",
    "Conference Manager",
    "Field Marketing Manager",
    "Regional Marketing Manager",
    "Local Marketing Manager",
    "Experiential Marketing Manager",
    "Sponsorship Manager",
  ],
  "Marketing - Research & Analytics": [
    "Market Research Manager",
    "Market Research Analyst",
    "Consumer Insights Manager",
    "Marketing Analyst",
    "Marketing Data Analyst",
    "Competitive Intelligence Analyst",
    "Customer Insights Analyst",
    "Voice of Customer Manager",
    "Market Intelligence Manager",
  ],

  // ========================
  // HUMAN RESOURCES ROLES (Comprehensive)
  // ========================
  "HR - Management": [
    "HR Manager",
    "Senior HR Manager",
    "HR Director",
    "Head of HR",
    "VP of HR",
    "CHRO",
    "HR Team Lead",
    "HR Supervisor",
    "Assistant HR Manager",
    "HR Admin",
    "HR Coordinator",
  ],
  "HR - Business Partnership": [
    "HR Business Partner",
    "Senior HR Business Partner",
    "Lead HRBP",
    "Regional HRBP",
    "HR Generalist",
    "Senior HR Generalist",
    "HR Executive",
    "HR Associate",
    "People Partner",
    "People Operations Manager",
    "Employee Relations Manager",
    "Employee Relations Specialist",
  ],
  "HR - Talent Acquisition": [
    "Recruiter",
    "Senior Recruiter",
    "Lead Recruiter",
    "Technical Recruiter",
    "IT Recruiter",
    "Campus Recruiter",
    "Executive Recruiter",
    "Headhunter",
    "Sourcing Specialist",
    "Talent Sourcer",
    "Talent Acquisition Specialist",
    "Talent Acquisition Partner",
    "Talent Acquisition Lead",
    "Talent Acquisition Manager",
    "Head of Talent Acquisition",
    "VP of Talent Acquisition",
    "Recruitment Manager",
    "Recruitment Coordinator",
    "Interview Coordinator",
    "Recruiting Operations Specialist",
  ],
  "HR - Compensation & Benefits": [
    "Compensation Manager",
    "Compensation Analyst",
    "Compensation & Benefits Manager",
    "Benefits Manager",
    "Benefits Specialist",
    "Benefits Administrator",
    "Total Rewards Manager",
    "Total Rewards Specialist",
    "Payroll Manager",
    "Payroll Specialist",
    "Payroll Administrator",
    "Payroll Executive",
    "HRIS Manager",
    "HRIS Analyst",
    "HRIS Administrator",
  ],
  "HR - Learning & Development": [
    "Learning & Development Manager",
    "L&D Specialist",
    "Training Manager",
    "Training Specialist",
    "Training Coordinator",
    "Corporate Trainer",
    "Technical Trainer",
    "Sales Trainer",
    "Soft Skills Trainer",
    "Instructional Designer",
    "eLearning Developer",
    "Organizational Development Manager",
    "OD Specialist",
    "Leadership Development Manager",
    "Talent Development Manager",
    "Performance Management Specialist",
    "Career Development Specialist",
  ],

  // ========================
  // FINANCE & ACCOUNTING ROLES (Comprehensive)
  // ========================
  "Finance - Management": [
    "Finance Manager",
    "Senior Finance Manager",
    "Finance Director",
    "Head of Finance",
    "VP of Finance",
    "CFO",
    "Finance Controller",
    "Financial Controller",
    "Assistant Finance Manager",
    "Finance Team Lead",
  ],
  "Finance - Analysis & Planning": [
    "Financial Analyst",
    "Senior Financial Analyst",
    "FP&A Analyst",
    "FP&A Manager",
    "Senior FP&A Analyst",
    "Financial Planning Manager",
    "Budget Analyst",
    "Budget Manager",
    "Business Finance Analyst",
    "Commercial Finance Manager",
    "Commercial Analyst",
    "Pricing Analyst",
    "Pricing Manager",
    "Revenue Analyst",
    "Investment Analyst",
    "Equity Research Analyst",
    "Credit Analyst",
    "Credit Risk Analyst",
    "Market Risk Analyst",
    "Quantitative Analyst",
  ],
  "Finance - Accounting": [
    "Accountant",
    "Senior Accountant",
    "Staff Accountant",
    "Junior Accountant",
    "Accounts Executive",
    "Accounts Manager",
    "Accounts Payable Specialist",
    "Accounts Payable Manager",
    "Accounts Receivable Specialist",
    "Accounts Receivable Manager",
    "General Ledger Accountant",
    "GL Accountant",
    "Cost Accountant",
    "Management Accountant",
    "Tax Accountant",
    "Tax Manager",
    "Tax Analyst",
    "Indirect Tax Manager",
    "GST Executive",
    "Tax Consultant",
  ],
  "Finance - Audit & Compliance": [
    "Internal Auditor",
    "Senior Auditor",
    "Audit Manager",
    "Audit Director",
    "External Auditor",
    "Statutory Auditor",
    "Compliance Manager",
    "Compliance Officer",
    "Compliance Analyst",
    "Regulatory Compliance Manager",
    "AML Analyst",
    "KYC Analyst",
    "KYC Manager",
    "Financial Crime Analyst",
    "Fraud Analyst",
    "Forensic Accountant",
    "SOX Compliance Manager",
  ],
  "Finance - Treasury & Banking": [
    "Treasury Manager",
    "Treasury Analyst",
    "Cash Manager",
    "Cash Management Specialist",
    "Forex Manager",
    "Forex Dealer",
    "Fund Manager",
    "Portfolio Manager",
    "Asset Manager",
    "Wealth Manager",
    "Relationship Manager - Banking",
    "Branch Manager - Bank",
    "Banking Operations Manager",
    "Trade Finance Manager",
    "Corporate Banking Manager",
    "Retail Banking Manager",
    "Investment Banking Analyst",
    "Investment Banking Associate",
    "M&A Analyst",
    "Venture Capital Analyst",
    "Private Equity Analyst",
  ],

  // ========================
  // OPERATIONS ROLES (Comprehensive)
  // ========================
  "Operations - Management": [
    "Operations Manager",
    "Senior Operations Manager",
    "Operations Director",
    "Head of Operations",
    "VP of Operations",
    "COO",
    "Operations Lead",
    "Operations Supervisor",
    "Assistant Operations Manager",
    "Operations Coordinator",
    "Operations Executive",
    "Operations Analyst",
    "Business Operations Manager",
    "Business Operations Analyst",
  ],
  "Operations - Process & Quality": [
    "Process Manager",
    "Process Improvement Manager",
    "Process Excellence Manager",
    "Process Analyst",
    "Business Process Analyst",
    "BPR Manager",
    "Quality Manager",
    "Quality Assurance Manager",
    "Quality Control Manager",
    "Quality Analyst",
    "Quality Engineer",
    "Six Sigma Black Belt",
    "Six Sigma Green Belt",
    "Lean Manager",
    "Continuous Improvement Manager",
    "ISO Auditor",
    "ISO Lead Auditor",
  ],
  "Operations - MIS & Reporting": [
    "MIS Manager",
    "MIS Executive",
    "MIS Analyst",
    "Reporting Manager",
    "Reporting Analyst",
    "Data Operations Manager",
    "Data Operations Analyst",
    "Dashboard Analyst",
    "BI Operations Analyst",
    "Operations Research Analyst",
    "Capacity Planning Manager",
    "Workforce Planning Manager",
    "Resource Planning Manager",
  ],

  // ========================
  // SUPPLY CHAIN & LOGISTICS
  // ========================
  "Supply Chain": [
    "Supply Chain Manager",
    "Senior Supply Chain Manager",
    "Supply Chain Director",
    "Head of Supply Chain",
    "VP of Supply Chain",
    "Supply Chain Analyst",
    "Supply Chain Planner",
    "Demand Planner",
    "Demand Planning Manager",
    "Supply Planner",
    "Supply Planning Manager",
    "S&OP Manager",
    "Inventory Manager",
    "Inventory Planner",
    "Inventory Analyst",
    "Inventory Controller",
    "Materials Manager",
    "Materials Planner",
  ],
  "Procurement & Sourcing": [
    "Procurement Manager",
    "Senior Procurement Manager",
    "Procurement Director",
    "Head of Procurement",
    "Chief Procurement Officer",
    "Procurement Specialist",
    "Procurement Executive",
    "Sourcing Manager",
    "Strategic Sourcing Manager",
    "Category Manager",
    "Vendor Manager",
    "Vendor Development Manager",
    "Supplier Quality Manager",
    "Purchase Manager",
    "Purchase Officer",
    "Buyer",
    "Senior Buyer",
    "Commodity Manager",
    "Contract Manager",
    "Contract Administrator",
  ],
  "Logistics & Distribution": [
    "Logistics Manager",
    "Senior Logistics Manager",
    "Logistics Director",
    "Head of Logistics",
    "Logistics Coordinator",
    "Logistics Executive",
    "Transportation Manager",
    "Fleet Manager",
    "Distribution Manager",
    "Distribution Center Manager",
    "Warehouse Manager",
    "Warehouse Supervisor",
    "Warehouse Executive",
    "Shipping Manager",
    "Import Export Manager",
    "Customs Manager",
    "Freight Manager",
    "Last Mile Delivery Manager",
    "Dispatch Manager",
    "Route Planner",
  ],

  // ========================
  // CUSTOMER SUCCESS & SUPPORT
  // ========================
  "Customer Success": [
    "Customer Success Manager",
    "Senior Customer Success Manager",
    "Customer Success Lead",
    "Head of Customer Success",
    "VP of Customer Success",
    "Director of Customer Success",
    "Customer Success Associate",
    "Customer Success Executive",
    "Enterprise Customer Success Manager",
    "SMB Customer Success Manager",
    "Customer Onboarding Manager",
    "Customer Onboarding Specialist",
    "Implementation Specialist",
    "Implementation Manager",
    "Solutions Architect",
    "Customer Consultant",
    "Client Services Manager",
    "Client Success Manager",
    "Account Management Associate",
    "Renewals Manager",
    "Retention Specialist",
  ],
  "Customer Support": [
    "Customer Support Executive",
    "Customer Support Specialist",
    "Customer Support Manager",
    "Customer Service Representative",
    "Customer Service Manager",
    "Customer Experience Manager",
    "CX Manager",
    "Support Team Lead",
    "Support Manager",
    "Technical Support Engineer",
    "Technical Support Specialist",
    "L1 Support Engineer",
    "L2 Support Engineer",
    "L3 Support Engineer",
    "Help Desk Analyst",
    "Service Desk Analyst",
    "Call Center Manager",
    "Call Center Team Lead",
    "Contact Center Manager",
    "Voice Process Executive",
    "Non-Voice Process Executive",
  ],

  // ========================
  // LEGAL & COMPLIANCE
  // ========================
  "Legal": [
    "Legal Counsel",
    "Senior Legal Counsel",
    "General Counsel",
    "Associate General Counsel",
    "Legal Manager",
    "Legal Director",
    "Head of Legal",
    "VP of Legal",
    "CLO",
    "Corporate Lawyer",
    "Corporate Counsel",
    "Commercial Lawyer",
    "IP Lawyer",
    "Employment Lawyer",
    "M&A Lawyer",
    "Litigation Manager",
    "Legal Associate",
    "Legal Executive",
    "Legal Officer",
    "Paralegal",
    "Company Secretary",
    "Assistant Company Secretary",
    "Corporate Secretary",
    "Legal Operations Manager",
    "Contract Specialist",
    "Contracts Manager",
    "Legal Analyst",
    "Compliance Officer",
    "Senior Compliance Officer",
    "Head of Compliance",
    "Chief Compliance Officer",
    "Regulatory Affairs Manager",
    "Regulatory Compliance Manager",
    "Risk & Compliance Manager",
    "Corporate Governance Manager",
    "Board Secretary",
    "Governance Officer",
  ],

  // ========================
  // CONSULTING & STRATEGY
  // ========================
  "Consulting & Strategy": [
    "Management Consultant",
    "Senior Management Consultant",
    "Strategy Consultant",
    "Business Consultant",
    "Technology Consultant",
    "IT Consultant",
    "Digital Consultant",
    "Digital Transformation Consultant",
    "Operations Consultant",
    "HR Consultant",
    "Financial Consultant",
    "Tax Consultant",
    "Risk Consultant",
    "Compliance Consultant",
    "Change Management Consultant",
    "Principal Consultant",
    "Associate Consultant",
    "Consulting Manager",
    "Consulting Director",
    "Partner - Consulting",
    "Strategy Manager",
    "Strategy Analyst",
    "Corporate Strategy Manager",
    "Business Strategy Manager",
    "Chief Strategy Officer",
    "Chief of Staff",
    "Business Transformation Manager",
  ],

  // ========================
  // BANKING & INSURANCE OPERATIONS
  // ========================
  "Banking Operations": [
    "Banking Operations Manager",
    "Branch Manager",
    "Assistant Branch Manager",
    "Branch Operations Manager",
    "Relationship Manager - Retail",
    "Relationship Manager - Corporate",
    "Relationship Manager - HNI",
    "Relationship Manager - NRI",
    "Personal Banker",
    "Premier Banker",
    "Priority Banker",
    "Loan Manager",
    "Loan Officer",
    "Credit Manager",
    "Credit Officer",
    "Mortgage Specialist",
    "Home Loan Advisor",
    "Business Loan Manager",
    "Collection Manager",
    "Recovery Manager",
    "Trade Operations Manager",
    "Payment Operations Manager",
    "Core Banking Operations",
    "CBS Administrator",
  ],
  "Insurance": [
    "Insurance Manager",
    "Insurance Advisor",
    "Insurance Agent",
    "Life Insurance Advisor",
    "General Insurance Manager",
    "Health Insurance Manager",
    "Motor Insurance Manager",
    "Underwriter",
    "Senior Underwriter",
    "Underwriting Manager",
    "Claims Manager",
    "Claims Processor",
    "Claims Adjuster",
    "Actuary",
    "Actuarial Analyst",
    "Policy Administrator",
    "Insurance Operations Manager",
    "Agency Manager",
    "Bancassurance Manager",
    "Reinsurance Manager",
  ],

  // ========================
  // REAL ESTATE
  // ========================
  "Real Estate": [
    "Real Estate Manager",
    "Real Estate Agent",
    "Real Estate Broker",
    "Property Manager",
    "Leasing Manager",
    "Leasing Executive",
    "Sales Manager - Real Estate",
    "Site Sales Manager",
    "CRM Manager - Real Estate",
    "Property Consultant",
    "Real Estate Consultant",
    "Real Estate Analyst",
    "Asset Manager - Real Estate",
    "Facilities Manager",
    "Facilities Coordinator",
    "Building Manager",
    "Estate Manager",
    "Commercial Real Estate Manager",
    "Residential Sales Manager",
    "Channel Sales Manager - Real Estate",
  ],

  // ========================
  // HOSPITALITY & TRAVEL
  // ========================
  "Hospitality": [
    "Hotel Manager",
    "General Manager - Hotel",
    "Resident Manager",
    "Front Office Manager",
    "Front Desk Manager",
    "Guest Relations Manager",
    "Reservations Manager",
    "Revenue Manager",
    "Rooms Division Manager",
    "Housekeeping Manager",
    "Executive Housekeeper",
    "F&B Manager",
    "Food & Beverage Director",
    "Restaurant Manager",
    "Banquet Manager",
    "Catering Manager",
    "Executive Chef",
    "Sous Chef",
    "Kitchen Manager",
    "Bar Manager",
    "Spa Manager",
    "Concierge Manager",
    "Night Manager",
  ],
  "Travel & Tourism": [
    "Travel Manager",
    "Travel Consultant",
    "Travel Agent",
    "Tour Manager",
    "Tour Operator",
    "Tourism Manager",
    "Destination Manager",
    "Holiday Consultant",
    "Corporate Travel Manager",
    "Travel Operations Manager",
    "Airline Manager",
    "Airport Manager",
    "Ground Handling Manager",
  ],

  // ========================
  // RETAIL & E-COMMERCE
  // ========================
  "Retail": [
    "Store Manager",
    "Assistant Store Manager",
    "Retail Manager",
    "Retail Operations Manager",
    "Area Manager - Retail",
    "Regional Manager - Retail",
    "Zonal Manager - Retail",
    "Visual Merchandiser",
    "Merchandising Manager",
    "Buyer - Retail",
    "Category Manager - Retail",
    "Inventory Manager - Retail",
    "Loss Prevention Manager",
    "Store Operations Manager",
    "Retail Sales Associate",
    "Department Manager",
    "Floor Manager",
    "Cashier Supervisor",
  ],
  "E-Commerce": [
    "E-Commerce Manager",
    "E-Commerce Director",
    "Head of E-Commerce",
    "Marketplace Manager",
    "Amazon Seller Manager",
    "Flipkart Account Manager",
    "Catalog Manager",
    "E-Commerce Operations Manager",
    "E-Commerce Marketing Manager",
    "Online Sales Manager",
    "D2C Manager",
    "Omnichannel Manager",
  ],

  // ========================
  // MANUFACTURING & PLANT
  // ========================
  "Manufacturing & Plant": [
    "Plant Manager",
    "Factory Manager",
    "Manufacturing Manager",
    "Production Manager",
    "Production Supervisor",
    "Production Planner",
    "Production Engineer",
    "Plant Head",
    "General Manager - Plant",
    "VP - Manufacturing",
    "Shift Manager",
    "Line Manager",
    "Assembly Line Supervisor",
    "Maintenance Manager",
    "Maintenance Engineer",
    "Industrial Engineer",
    "Process Engineer",
    "Tool Room Manager",
    "Store Manager - Factory",
    "Safety Manager",
    "EHS Manager",
    "Environment Health Safety Manager",
  ],

  // ========================
  // ADMIN & OFFICE MANAGEMENT
  // ========================
  "Administration": [
    "Admin Manager",
    "Administration Manager",
    "Office Manager",
    "Office Administrator",
    "Admin Executive",
    "Admin Assistant",
    "Administrative Assistant",
    "Executive Assistant",
    "Personal Assistant",
    "Secretary",
    "Executive Secretary",
    "Senior Secretary",
    "Receptionist",
    "Front Desk Executive",
    "Office Coordinator",
    "Facilities Coordinator",
    "Travel Desk Executive",
    "Vendor Coordinator",
    "Admin Supervisor",
    "General Affairs Manager",
  ],
};

// Flatten for dropdown with categories
export const ALL_ROLES = Object.entries(JOB_ROLES).flatMap(([category, roles]) =>
  roles.map(role => ({ value: role, label: role, category }))
);

// ============================================================================
// SKILLS DATABASE - 700+ skills across categories
// ============================================================================

export const SKILLS = {
  // ========================
  // TECHNICAL SKILLS
  // ========================
  "Programming Languages": [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C++",
    "C#",
    "Go",
    "Rust",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "Scala",
    "R",
    "MATLAB",
    "Perl",
    "Shell Scripting",
    "Bash",
    "PowerShell",
    "SQL",
    "PL/SQL",
    "Groovy",
    "Dart",
    "Lua",
    "Objective-C",
    "COBOL",
    "Fortran",
    "Assembly",
    "Haskell",
    "Elixir",
    "Clojure",
  ],

  "Frontend Development": [
    "React",
    "Angular",
    "Vue.js",
    "Next.js",
    "Nuxt.js",
    "Svelte",
    "jQuery",
    "HTML5",
    "CSS3",
    "SASS/SCSS",
    "Less",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Chakra UI",
    "Styled Components",
    "Redux",
    "MobX",
    "Zustand",
    "React Query",
    "GraphQL Client",
    "Webpack",
    "Vite",
    "Babel",
    "ESLint",
    "Jest",
    "Cypress",
    "Playwright",
    "Storybook",
    "Responsive Design",
    "Web Accessibility (WCAG)",
    "PWA Development",
  ],

  "Backend Development": [
    "Node.js",
    "Express.js",
    "NestJS",
    "Django",
    "Flask",
    "FastAPI",
    "Spring Boot",
    "Spring Framework",
    "Hibernate",
    "ASP.NET Core",
    ".NET Framework",
    "Ruby on Rails",
    "Laravel",
    "Symfony",
    "CodeIgniter",
    "Gin",
    "Echo",
    "Fiber",
    "Actix",
    "Phoenix",
    "REST APIs",
    "GraphQL",
    "gRPC",
    "WebSockets",
    "Message Queues",
    "Microservices",
    "Event-Driven Architecture",
    "CQRS",
    "Domain-Driven Design",
  ],

  "Databases": [
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "Oracle Database",
    "Microsoft SQL Server",
    "SQLite",
    "Cassandra",
    "DynamoDB",
    "Firebase",
    "Supabase",
    "Neo4j",
    "CouchDB",
    "InfluxDB",
    "TimescaleDB",
    "MariaDB",
    "Memcached",
    "Apache HBase",
    "Amazon RDS",
    "Database Design",
    "Query Optimization",
    "Database Administration",
  ],

  "Cloud & DevOps": [
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI/CD",
    "CircleCI",
    "ArgoCD",
    "Helm",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "Datadog",
    "New Relic",
    "Splunk",
    "AWS Lambda",
    "Azure Functions",
    "CloudFormation",
    "Pulumi",
    "Nginx",
    "Apache",
    "HAProxy",
    "Load Balancing",
    "CDN (Cloudflare/Akamai)",
    "Linux Administration",
    "Shell Scripting",
    "Infrastructure as Code",
    "Site Reliability Engineering",
    "Monitoring & Alerting",
  ],

  "Mobile Development": [
    "React Native",
    "Flutter",
    "iOS Development",
    "Android Development",
    "SwiftUI",
    "Jetpack Compose",
    "Xamarin",
    "Ionic",
    "Capacitor",
    "Cordova",
    "Mobile UI/UX",
    "App Store Optimization",
    "Push Notifications",
    "Mobile Analytics",
    "Firebase (Mobile)",
    "CoreData",
    "Room Database",
  ],

  "Data & AI/ML": [
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "Apache Spark",
    "Apache Kafka",
    "Apache Airflow",
    "Databricks",
    "Snowflake",
    "Data Warehousing",
    "ETL Pipelines",
    "Data Modeling",
    "Feature Engineering",
    "A/B Testing",
    "Statistical Analysis",
    "Predictive Modeling",
    "Recommendation Systems",
    "LLMs & Prompt Engineering",
    "MLOps",
    "OpenAI API",
    "Hugging Face",
    "Langchain",
    "RAG (Retrieval Augmented Generation)",
  ],

  "Testing & Quality Assurance": [
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Performance Testing",
    "Load Testing",
    "Security Testing",
    "API Testing",
    "Selenium",
    "Appium",
    "JMeter",
    "Locust",
    "Postman",
    "SoapUI",
    "TestNG",
    "JUnit",
    "PyTest",
    "Mocha",
    "Chai",
    "Test Automation",
    "BDD/TDD",
    "Cucumber",
    "Robot Framework",
  ],

  "Security": [
    "Application Security",
    "Cloud Security",
    "Network Security",
    "OWASP Top 10",
    "Penetration Testing",
    "Vulnerability Assessment",
    "SIEM",
    "SOC Operations",
    "Identity & Access Management",
    "OAuth/OIDC",
    "JWT",
    "SSL/TLS",
    "Encryption",
    "Compliance (SOC2, GDPR, HIPAA)",
    "Security Auditing",
    "Threat Modeling",
    "Incident Response",
  ],

  // ========================
  // SALES & BUSINESS DEVELOPMENT SKILLS
  // ========================
  "Sales Strategy & Execution": [
    "Sales Strategy",
    "Sales Planning",
    "Sales Forecasting",
    "Territory Planning",
    "Territory Management",
    "Quota Achievement",
    "Revenue Growth",
    "Pipeline Management",
    "Sales Pipeline Development",
    "Sales Cycle Management",
    "Deal Closure",
    "Closing Techniques",
    "Sales Negotiations",
    "Pricing Strategy",
    "Discount Management",
    "Sales Target Setting",
    "Sales Performance Management",
    "Sales Analytics",
    "Win-Loss Analysis",
    "Market Penetration",
    "Market Expansion",
    "Go-to-Market Strategy",
    "Revenue Operations",
    "Sales Operations",
  ],
  "Lead Generation & Prospecting": [
    "Lead Generation",
    "Lead Qualification",
    "Lead Scoring",
    "Lead Nurturing",
    "Prospect Research",
    "Prospecting",
    "Cold Calling",
    "Cold Emailing",
    "Email Outreach",
    "LinkedIn Prospecting",
    "Social Selling",
    "Outbound Sales",
    "Inbound Sales",
    "Inside Sales",
    "Field Sales",
    "Door-to-Door Sales",
    "Telemarketing",
    "Appointment Setting",
    "Demo Scheduling",
  ],
  "Account & Relationship Management": [
    "Key Account Management",
    "Strategic Account Management",
    "Account Planning",
    "Account Development",
    "Customer Relationship Management",
    "Client Relationship Building",
    "Relationship Building",
    "Client Retention",
    "Customer Retention",
    "Upselling",
    "Cross-selling",
    "Renewals Management",
    "Contract Renewals",
    "Customer Lifetime Value",
    "Client Portfolio Management",
    "Enterprise Selling",
    "Solution Selling",
    "Consultative Selling",
    "Value-Based Selling",
    "Challenger Sales",
  ],
  "Channel & Partnership Sales": [
    "Channel Sales",
    "Channel Development",
    "Channel Partner Management",
    "Partner Recruitment",
    "Partner Enablement",
    "Distribution Management",
    "Distributor Management",
    "Dealer Management",
    "Franchise Development",
    "Reseller Management",
    "Alliance Building",
    "Strategic Partnerships",
    "Partnership Development",
    "Co-selling",
    "Referral Programs",
    "Affiliate Sales",
  ],
  "B2B & B2C Sales": [
    "B2B Sales",
    "B2C Sales",
    "Enterprise Sales",
    "Mid-Market Sales",
    "SMB Sales",
    "Corporate Sales",
    "Government Sales",
    "Public Sector Sales",
    "Retail Sales",
    "Direct Sales",
    "Indirect Sales",
    "eCommerce Sales",
    "Marketplace Sales",
    "SaaS Sales",
    "Technology Sales",
    "Software Sales",
    "Hardware Sales",
    "Services Sales",
    "Subscription Sales",
  ],
  "CRM & Sales Tools": [
    "CRM (Salesforce)",
    "Salesforce Admin",
    "Salesforce Sales Cloud",
    "CRM (HubSpot)",
    "HubSpot Sales Hub",
    "CRM (Zoho)",
    "Zoho CRM",
    "CRM (Microsoft Dynamics)",
    "CRM (Pipedrive)",
    "CRM (Freshsales)",
    "Sales Navigator",
    "LinkedIn Sales Navigator",
    "ZoomInfo",
    "Apollo.io",
    "Outreach.io",
    "SalesLoft",
    "Gong.io",
    "Chorus.ai",
    "Clari",
    "Sales Enablement Tools",
  ],

  // ========================
  // MARKETING SKILLS
  // ========================
  "Digital Marketing": [
    "Digital Marketing Strategy",
    "Digital Marketing Planning",
    "Marketing Automation",
    "Marketing Technology (MarTech)",
    "Customer Journey Mapping",
    "Omnichannel Marketing",
    "Multi-channel Marketing",
    "Integrated Marketing",
    "Inbound Marketing",
    "Outbound Marketing",
    "Permission Marketing",
    "Direct Response Marketing",
    "B2B Marketing",
    "B2C Marketing",
    "D2C Marketing",
    "Consumer Marketing",
    "Enterprise Marketing",
    "Product Marketing",
    "Growth Marketing",
    "Full-Funnel Marketing",
  ],
  "Performance Marketing & Paid Media": [
    "Performance Marketing",
    "Paid Media",
    "PPC Management",
    "SEM",
    "Search Engine Marketing",
    "Google Ads",
    "Google Search Ads",
    "Google Display Ads",
    "Google Shopping Ads",
    "YouTube Ads",
    "Meta Ads",
    "Facebook Ads",
    "Instagram Ads",
    "LinkedIn Ads",
    "Twitter Ads",
    "TikTok Ads",
    "Snapchat Ads",
    "Pinterest Ads",
    "Programmatic Advertising",
    "Display Advertising",
    "Retargeting",
    "Remarketing",
    "Native Advertising",
    "Affiliate Marketing",
    "Mobile Advertising",
    "App Install Campaigns",
    "ROAS Optimization",
    "CAC Optimization",
    "LTV to CAC Ratio",
  ],
  "SEO & Content": [
    "SEO",
    "Search Engine Optimization",
    "Technical SEO",
    "On-Page SEO",
    "Off-Page SEO",
    "Local SEO",
    "International SEO",
    "E-commerce SEO",
    "YouTube SEO",
    "App Store Optimization (ASO)",
    "Link Building",
    "Backlink Strategy",
    "Keyword Research",
    "Keyword Strategy",
    "Content Marketing",
    "Content Strategy",
    "Content Planning",
    "Content Calendar",
    "Editorial Planning",
    "Blog Management",
    "Article Writing",
    "Long-form Content",
    "Pillar Content",
    "Evergreen Content",
    "Content Distribution",
    "Content Syndication",
    "Guest Posting",
    "Copywriting",
    "Sales Copywriting",
    "Email Copywriting",
    "Ad Copywriting",
    "Landing Page Copy",
    "UX Writing",
    "Technical Writing",
    "White Papers",
    "Case Studies",
    "eBooks",
  ],
  "Email & CRM Marketing": [
    "Email Marketing",
    "Email Campaign Management",
    "Email Automation",
    "Drip Campaigns",
    "Welcome Sequences",
    "Newsletter Management",
    "Email List Building",
    "Email Segmentation",
    "Email Personalization",
    "Email Deliverability",
    "A/B Testing (Email)",
    "CRM Marketing",
    "Lifecycle Marketing",
    "Retention Marketing",
    "Win-back Campaigns",
    "Lead Nurturing Campaigns",
    "HubSpot Marketing",
    "Mailchimp",
    "Klaviyo",
    "ActiveCampaign",
    "Marketo",
    "Pardot",
    "Intercom",
    "Customer.io",
    "Braze",
    "Iterable",
  ],
  "Social Media Marketing": [
    "Social Media Marketing",
    "Social Media Strategy",
    "Social Media Management",
    "Social Media Content",
    "Social Media Advertising",
    "Facebook Marketing",
    "Instagram Marketing",
    "LinkedIn Marketing",
    "Twitter Marketing",
    "TikTok Marketing",
    "YouTube Marketing",
    "Pinterest Marketing",
    "Influencer Marketing",
    "Influencer Outreach",
    "Creator Partnerships",
    "User-Generated Content",
    "Community Management",
    "Community Building",
    "Social Listening",
    "Social Media Analytics",
    "Hootsuite",
    "Buffer",
    "Sprout Social",
    "Later",
  ],
  "Brand & Communications": [
    "Brand Strategy",
    "Brand Building",
    "Brand Positioning",
    "Brand Architecture",
    "Brand Guidelines",
    "Brand Identity",
    "Brand Messaging",
    "Brand Voice",
    "Brand Storytelling",
    "Employer Branding",
    "Corporate Branding",
    "Personal Branding",
    "Rebranding",
    "Communications Strategy",
    "Corporate Communications",
    "Internal Communications",
    "External Communications",
    "Public Relations",
    "Media Relations",
    "Press Releases",
    "Media Outreach",
    "Crisis Communications",
    "Reputation Management",
    "Thought Leadership",
    "Spokesperson Training",
  ],
  "Analytics & Insights": [
    "Marketing Analytics",
    "Marketing Attribution",
    "Multi-touch Attribution",
    "Marketing Mix Modeling",
    "Google Analytics",
    "GA4",
    "Adobe Analytics",
    "Mixpanel",
    "Amplitude",
    "Heap Analytics",
    "Hotjar",
    "Crazy Egg",
    "Segment",
    "Customer Data Platform",
    "Market Research",
    "Market Analysis",
    "Competitive Analysis",
    "Consumer Research",
    "Customer Insights",
    "Voice of Customer",
    "NPS Analysis",
    "Survey Design",
    "Focus Groups",
    "User Research",
  ],
  "Conversion & Growth": [
    "Conversion Rate Optimization",
    "CRO",
    "A/B Testing",
    "Multivariate Testing",
    "Landing Page Optimization",
    "Funnel Optimization",
    "Growth Hacking",
    "Growth Experiments",
    "Rapid Experimentation",
    "User Acquisition",
    "Customer Acquisition",
    "Viral Marketing",
    "Referral Marketing",
    "Product-Led Growth",
    "Freemium Strategy",
    "Onboarding Optimization",
    "Activation Optimization",
    "Retention Optimization",
  ],

  // ========================
  // HR & TALENT SKILLS
  // ========================
  "Talent Acquisition & Recruiting": [
    "Talent Acquisition",
    "Full Cycle Recruiting",
    "Technical Recruiting",
    "IT Recruiting",
    "Executive Recruiting",
    "Leadership Hiring",
    "Campus Recruiting",
    "Graduate Hiring",
    "Volume Hiring",
    "Mass Recruitment",
    "Sourcing",
    "Boolean Search",
    "X-Ray Search",
    "LinkedIn Recruiter",
    "Headhunting",
    "Passive Candidate Sourcing",
    "Candidate Pipeline Building",
    "Talent Mapping",
    "Market Mapping",
    "Competitive Intelligence (HR)",
    "ATS (Greenhouse)",
    "ATS (Lever)",
    "ATS (Workday)",
    "ATS (iCIMS)",
    "ATS (Taleo)",
    "Interview Scheduling",
    "Interview Coordination",
    "Candidate Assessment",
    "Competency-Based Interviewing",
    "Behavioral Interviewing",
    "Structured Interviews",
    "Reference Checks",
    "Background Verification",
    "Offer Management",
    "Offer Negotiation",
    "Onboarding",
    "Pre-boarding",
    "Recruitment Marketing",
    "Employer Branding",
    "Career Page Management",
    "Job Description Writing",
    "Diversity Hiring",
    "DEI Recruiting",
    "Recruitment Analytics",
    "Time-to-Hire Optimization",
    "Cost-per-Hire Analysis",
  ],
  "HR Operations & Administration": [
    "HR Operations",
    "HR Administration",
    "HR Policies",
    "HR Policy Development",
    "Employee Handbook",
    "HR Compliance",
    "Labor Law Compliance",
    "Employment Law",
    "Labor Law Basics",
    "Industrial Relations",
    "POSH Compliance",
    "HR Audits",
    "HRIS Management",
    "Workday",
    "SAP SuccessFactors",
    "BambooHR",
    "ADP",
    "Payroll Management",
    "Payroll Processing",
    "Compensation Administration",
    "Benefits Administration",
    "Leave Management",
    "Attendance Management",
    "Employee Records Management",
    "HR Reporting",
    "HR Analytics",
    "People Analytics",
    "HR Metrics",
    "Workforce Planning",
    "Headcount Planning",
  ],
  "Employee Engagement & Relations": [
    "Employee Engagement",
    "Employee Experience",
    "Employee Relations",
    "Conflict Resolution",
    "Grievance Handling",
    "Disciplinary Actions",
    "Performance Improvement Plans",
    "Exit Management",
    "Exit Interviews",
    "Retention Strategies",
    "Employee Satisfaction Surveys",
    "Pulse Surveys",
    "eNPS",
    "Town Halls",
    "Skip-Level Meetings",
    "Culture Building",
    "Organizational Culture",
    "Culture Transformation",
    "Diversity & Inclusion",
    "DEI Programs",
    "Belonging Initiatives",
    "Employee Resource Groups",
    "Workplace Wellness",
    "Employee Wellbeing",
    "Mental Health Initiatives",
  ],
  "Learning & Development": [
    "Learning & Development",
    "L&D Strategy",
    "Training Needs Analysis",
    "Training Design",
    "Training Delivery",
    "Corporate Training",
    "Technical Training",
    "Soft Skills Training",
    "Leadership Training",
    "Management Development",
    "Leadership Development",
    "Executive Coaching",
    "Mentorship Programs",
    "Coaching",
    "Instructional Design",
    "Curriculum Development",
    "eLearning Development",
    "LMS Administration",
    "Articulate",
    "Captivate",
    "Storyline",
    "SCORM",
    "Competency Frameworks",
    "Skills Assessment",
    "Career Development",
    "Career Pathing",
    "Succession Planning",
    "High Potential Programs",
  ],
  "Performance & Compensation": [
    "Performance Management",
    "Goal Setting",
    "OKRs",
    "KPIs",
    "Performance Reviews",
    "360 Feedback",
    "Continuous Feedback",
    "Performance Calibration",
    "Compensation Strategy",
    "Compensation Benchmarking",
    "Salary Surveys",
    "Pay Equity Analysis",
    "Job Evaluation",
    "Job Grading",
    "Variable Pay",
    "Incentive Design",
    "Commission Structures",
    "Bonus Programs",
    "ESOP/Stock Options",
    "Total Rewards",
    "Benefits Design",
    "Health Insurance Management",
    "Retirement Benefits",
    "Perks & Recognition",
  ],

  // ========================
  // FINANCE & ACCOUNTING SKILLS
  // ========================
  "Financial Analysis & Planning": [
    "Financial Analysis",
    "Financial Modeling",
    "3-Statement Modeling",
    "DCF Modeling",
    "LBO Modeling",
    "Merger Model",
    "Scenario Analysis",
    "Sensitivity Analysis",
    "FP&A",
    "Financial Planning",
    "Budgeting",
    "Budget Management",
    "Annual Budget Planning",
    "Rolling Forecasts",
    "Forecasting",
    "Variance Analysis",
    "Trend Analysis",
    "Financial Reporting",
    "Management Reporting",
    "Board Reporting",
    "Investor Reporting",
    "Financial Presentations",
    "Business Case Development",
    "ROI Analysis",
    "NPV Analysis",
    "IRR Calculation",
    "Payback Period Analysis",
    "Break-even Analysis",
    "Profitability Analysis",
    "Margin Analysis",
    "Working Capital Management",
    "Cash Flow Management",
    "Cash Flow Forecasting",
  ],
  "Accounting & Bookkeeping": [
    "Accounting",
    "Financial Accounting",
    "Management Accounting",
    "Cost Accounting",
    "Activity-Based Costing",
    "Standard Costing",
    "GAAP",
    "IFRS",
    "Ind AS",
    "Revenue Recognition",
    "Lease Accounting",
    "Inventory Accounting",
    "Fixed Assets Accounting",
    "Accounts Payable",
    "AP Processing",
    "Invoice Processing",
    "Vendor Payments",
    "Accounts Receivable",
    "AR Collections",
    "Credit Control",
    "General Ledger",
    "Journal Entries",
    "Month-End Close",
    "Quarter-End Close",
    "Year-End Close",
    "Bank Reconciliation",
    "Intercompany Reconciliation",
    "Consolidation",
    "Financial Consolidation",
    "Bookkeeping",
  ],
  "Tax & Compliance": [
    "Tax Planning",
    "Tax Compliance",
    "Corporate Tax",
    "Income Tax",
    "GST",
    "VAT",
    "Sales Tax",
    "Indirect Tax",
    "Direct Tax",
    "Transfer Pricing",
    "International Tax",
    "Tax Returns",
    "Tax Audits",
    "Statutory Compliance",
    "ROC Filings",
    "Secretarial Compliance",
    "Companies Act",
    "SEBI Regulations",
    "SOX Compliance",
    "Internal Controls",
    "ICFR",
  ],
  "Audit & Risk": [
    "Internal Audit",
    "External Audit",
    "Statutory Audit",
    "Audit Planning",
    "Audit Execution",
    "Audit Reporting",
    "Risk Assessment",
    "Risk Management",
    "Enterprise Risk Management",
    "Operational Risk",
    "Financial Risk",
    "Market Risk",
    "Credit Risk",
    "Liquidity Risk",
    "Fraud Detection",
    "Fraud Investigation",
    "Forensic Accounting",
    "Internal Control Testing",
    "Process Audits",
    "Compliance Audits",
  ],
  "Finance Tools & Systems": [
    "Excel (Advanced)",
    "Excel Macros",
    "VBA",
    "Power Query",
    "Power Pivot",
    "Power BI",
    "Tableau",
    "Looker",
    "SAP FICO",
    "SAP S/4HANA",
    "Oracle Financials",
    "Oracle EBS",
    "NetSuite",
    "Workday Finance",
    "QuickBooks",
    "Xero",
    "Tally",
    "Zoho Books",
    "Hyperion",
    "Anaplan",
    "Adaptive Insights",
    "BlackLine",
    "Coupa",
  ],
  "Insurance Technology": [
    "Guidewire",
    "Guidewire PolicyCenter",
    "Guidewire ClaimCenter",
    "Guidewire BillingCenter",
    "Guidewire InsuranceSuite",
    "Guidewire Cloud",
    "Duck Creek",
    "Duck Creek Policy",
    "Duck Creek Billing",
    "Duck Creek Claims",
    "Majesco",
    "Insurity",
    "FINEOS",
    "EIS Group",
    "Sapiens",
    "Socotra",
    "Insurance Core Systems",
    "Policy Administration",
    "Claims Management",
    "Billing Systems",
    "Underwriting Systems",
    "Insurance Analytics",
    "Actuarial Systems",
    "Reinsurance",
    "ACORD Standards",
    "Insurance APIs",
    "Insurtech",
  ],
  "Legal & Corporate Governance": [
    "Corporate Law",
    "Commercial Law",
    "Contract Law",
    "Contract Drafting",
    "Contract Review",
    "Contract Management",
    "Contract Negotiation",
    "Legal Documentation",
    "Legal Drafting",
    "Corporate Governance",
    "Board Advisory",
    "Board Meetings",
    "Shareholder Agreements",
    "JV Agreements",
    "M&A Documentation",
    "Due Diligence",
    "Legal Due Diligence",
    "IPR Management",
    "Patent Filing",
    "Trademark Registration",
    "Litigation Management",
    "Dispute Resolution",
    "Arbitration",
    "Mediation",
    "Regulatory Compliance",
    "Legal Compliance",
    "Secretarial Compliance",
    "Companies Act Compliance",
    "SEBI Compliance",
    "RBI Compliance",
    "FEMA Compliance",
    "MCA Filings",
    "ROC Filings",
    "Annual Returns",
    "EPC Contracts",
    "O&M Agreements",
    "PPA Negotiation",
    "Land Aggregation",
    "Title Verification",
    "Right of Way",
    "Permits & Approvals",
    "Regulatory Liaison",
  ],
  "Wealth & Investment Management": [
    "Wealth Management",
    "Portfolio Management",
    "Investment Management",
    "Asset Management",
    "Mutual Funds",
    "Equity Research",
    "Fixed Income",
    "Debt Markets",
    "Capital Markets",
    "Financial Planning",
    "Retirement Planning",
    "Tax Planning (Personal)",
    "Estate Planning",
    "Succession Planning",
    "Investment Advisory",
    "Client Relationship Management",
    "HNI Client Management",
    "UHNI Client Management",
    "Family Office",
    "Private Banking",
    "Investment Banking",
    "Mergers & Acquisitions",
    "Valuations",
    "Financial Modeling",
    "DCF Analysis",
    "Comparable Analysis",
    "Transaction Advisory",
    "Pitch Books",
    "Deal Structuring",
    "Fund Management",
    "AIF Management",
    "PMS",
    "Alternative Investments",
    "Real Estate Investments",
    "Private Equity",
    "Venture Capital",
  ],
  "Proposal & Bid Management": [
    "RFP Management",
    "RFI Management",
    "RFQ Management",
    "DDQ Management",
    "Proposal Writing",
    "Proposal Management",
    "Bid Management",
    "Tender Management",
    "Technical Writing",
    "Solution Writing",
    "Pricing Strategy",
    "Competitive Pricing",
    "Win Strategy",
    "Proposal Coordination",
    "Client Presentations",
    "Orals Preparation",
    "Pursuit Management",
  ],

  // ========================
  // OPERATIONS & PROCESS SKILLS
  // ========================
  "Operations Management": [
    "Operations Management",
    "Operations Planning",
    "Operations Strategy",
    "Capacity Planning",
    "Resource Planning",
    "Resource Allocation",
    "Workforce Management",
    "Shift Planning",
    "Scheduling",
    "Production Planning",
    "Production Scheduling",
    "Master Production Schedule",
    "Shop Floor Management",
    "OEE Management",
    "Downtime Management",
    "Maintenance Planning",
    "Preventive Maintenance",
    "Predictive Maintenance",
    "TPM",
    "Asset Management",
    "Facility Management",
  ],
  "Process Excellence": [
    "Process Improvement",
    "Process Optimization",
    "Process Reengineering",
    "Business Process Management",
    "Process Mapping",
    "Process Documentation",
    "SOP Development",
    "Lean Manufacturing",
    "Lean Management",
    "Lean Six Sigma",
    "Six Sigma",
    "Six Sigma Green Belt",
    "Six Sigma Black Belt",
    "DMAIC",
    "Kaizen",
    "5S",
    "Value Stream Mapping",
    "Root Cause Analysis",
    "Pareto Analysis",
    "Fishbone Diagram",
    "5 Whys",
    "FMEA",
    "SPC",
    "TQM",
    "Continuous Improvement",
    "Operational Excellence",
    "Agile Operations",
  ],
  "Quality Management": [
    "Quality Management",
    "Quality Assurance",
    "Quality Control",
    "Quality Planning",
    "Quality Audits",
    "ISO 9001",
    "ISO 14001",
    "ISO 27001",
    "ISO 45001",
    "IATF 16949",
    "AS9100",
    "GMP",
    "HACCP",
    "FDA Compliance",
    "CE Marking",
    "Quality Documentation",
    "Incoming Quality Control",
    "In-Process Quality Control",
    "Final Inspection",
    "Supplier Quality Management",
    "Customer Quality Management",
    "Quality Metrics",
    "PPM Management",
    "First Pass Yield",
    "Defect Analysis",
    "CAPA",
    "8D Problem Solving",
  ],
  "MIS & Reporting": [
    "MIS Reporting",
    "Dashboard Development",
    "KPI Tracking",
    "KPI Reporting",
    "Performance Dashboards",
    "Executive Dashboards",
    "Operational Reporting",
    "Daily Reporting",
    "Weekly Reporting",
    "Monthly Reporting",
    "Automated Reporting",
    "Report Automation",
    "Data Visualization",
    "Power BI Dashboards",
    "Tableau Dashboards",
    "Google Data Studio",
    "Excel Dashboards",
    "Data Analysis",
    "Trend Analysis",
    "Descriptive Analytics",
    "Business Intelligence",
  ],

  // ========================
  // SUPPLY CHAIN & LOGISTICS SKILLS
  // ========================
  "Supply Chain Management": [
    "Supply Chain Management",
    "Supply Chain Strategy",
    "Supply Chain Planning",
    "S&OP",
    "Sales & Operations Planning",
    "IBP",
    "Integrated Business Planning",
    "Demand Planning",
    "Demand Forecasting",
    "Supply Planning",
    "Material Planning",
    "MRP",
    "MRP II",
    "Inventory Management",
    "Inventory Optimization",
    "Safety Stock Planning",
    "EOQ",
    "ABC Analysis",
    "XYZ Analysis",
    "Inventory Turns",
    "OTIF Management",
    "Fill Rate Management",
    "Lead Time Reduction",
    "Supply Chain Analytics",
    "Supply Chain Visibility",
    "Control Tower",
  ],
  "Procurement & Sourcing": [
    "Strategic Sourcing",
    "Category Management",
    "Spend Analysis",
    "Supplier Selection",
    "Supplier Evaluation",
    "Supplier Development",
    "Supplier Relationship Management",
    "Vendor Management",
    "Vendor Negotiation",
    "Contract Negotiation",
    "Procurement Negotiation",
    "Cost Negotiation",
    "RFQ Management",
    "RFP Management",
    "Tender Management",
    "Purchase Order Management",
    "Procurement Analytics",
    "Cost Reduction",
    "TCO Analysis",
    "Make vs Buy Analysis",
    "Supplier Audits",
    "Supplier Scorecards",
    "E-Procurement",
    "SAP MM",
    "SAP Ariba",
    "Coupa Procurement",
    "Oracle Procurement",
  ],
  "Logistics & Distribution": [
    "Logistics Management",
    "Transportation Management",
    "Fleet Management",
    "Route Optimization",
    "Last Mile Delivery",
    "First Mile Pickup",
    "Freight Management",
    "Freight Forwarding",
    "3PL Management",
    "4PL Management",
    "Carrier Management",
    "Rate Negotiation",
    "TMS",
    "Transportation Management System",
    "Warehouse Management",
    "WMS",
    "Warehouse Operations",
    "Warehouse Layout Design",
    "Pick Pack Ship",
    "Cross Docking",
    "Distribution Network Design",
    "Hub and Spoke",
    "Import Export",
    "Customs Clearance",
    "Incoterms",
    "Trade Compliance",
    "Dangerous Goods Handling",
    "Cold Chain Logistics",
    "Reverse Logistics",
    "Returns Management",
  ],

  // ========================
  // CUSTOMER SUCCESS & SERVICE SKILLS
  // ========================
  "Customer Success": [
    "Customer Success Management",
    "Customer Onboarding",
    "Customer Adoption",
    "Customer Health Scoring",
    "Churn Prevention",
    "Churn Analysis",
    "Customer Retention",
    "Customer Expansion",
    "Upsell Management",
    "Cross-sell Management",
    "Renewal Management",
    "QBR Management",
    "Business Reviews",
    "Customer Advocacy",
    "Customer References",
    "Case Studies Development",
    "NPS Management",
    "CSAT Management",
    "Customer Feedback Management",
    "Voice of Customer",
    "Customer Journey Management",
    "Success Planning",
    "Value Realization",
    "ROI Demonstration",
    "Gainsight",
    "ChurnZero",
    "Totango",
    "ClientSuccess",
  ],
  "Customer Service & Support": [
    "Customer Service",
    "Customer Support",
    "Technical Support",
    "Help Desk",
    "Service Desk",
    "L1 Support",
    "L2 Support",
    "L3 Support",
    "Ticket Management",
    "Incident Management",
    "Problem Management",
    "Escalation Management",
    "SLA Management",
    "First Call Resolution",
    "Average Handle Time",
    "Customer Complaint Handling",
    "Query Resolution",
    "Chat Support",
    "Email Support",
    "Phone Support",
    "Call Center Operations",
    "Contact Center Operations",
    "IVR Management",
    "Knowledge Base Management",
    "Self-Service Portals",
    "Zendesk",
    "Freshdesk",
    "ServiceNow",
    "Salesforce Service Cloud",
    "Intercom",
  ],

  // ========================
  // PROJECT & PROGRAM MANAGEMENT SKILLS
  // ========================
  "Project Management": [
    "Project Management",
    "Project Planning",
    "Project Scheduling",
    "Gantt Charts",
    "Work Breakdown Structure",
    "Critical Path Method",
    "Project Budgeting",
    "Project Cost Management",
    "Project Risk Management",
    "Risk Identification",
    "Risk Mitigation",
    "Issue Management",
    "Change Management",
    "Scope Management",
    "Requirements Management",
    "Stakeholder Management",
    "Project Communication",
    "Status Reporting",
    "Project Documentation",
    "Project Governance",
    "PMO",
    "PMP",
    "PRINCE2",
    "CAPM",
    "Agile Project Management",
    "Waterfall Methodology",
    "Hybrid Project Management",
    "MS Project",
    "Primavera",
    "Smartsheet",
    "Monday.com",
    "Asana",
    "Trello",
    "Jira",
    "Confluence",
  ],
  "Agile & Scrum": [
    "Agile Methodology",
    "Scrum",
    "Scrum Master",
    "Product Owner",
    "Sprint Planning",
    "Sprint Review",
    "Sprint Retrospective",
    "Daily Standups",
    "Backlog Management",
    "Product Backlog",
    "Sprint Backlog",
    "User Story Writing",
    "Acceptance Criteria",
    "Story Points",
    "Velocity Tracking",
    "Burndown Charts",
    "Burnup Charts",
    "Kanban",
    "Lean Agile",
    "SAFe",
    "Scaled Agile Framework",
    "LeSS",
    "Agile Coaching",
    "Agile Transformation",
    "DevOps Integration",
    "Continuous Delivery",
  ],

  // ========================
  // COMMUNICATION & SOFT SKILLS
  // ========================
  "Communication & Soft Skills": [
    "Communication Skills",
    "Written Communication",
    "Verbal Communication",
    "Business Communication",
    "Email Communication",
    "Presentation Skills",
    "Public Speaking",
    "Storytelling",
    "Active Listening",
    "Negotiation Skills",
    "Persuasion",
    "Influence",
    "Stakeholder Management",
    "Executive Communication",
    "Client Communication",
    "Cross-functional Collaboration",
    "Team Collaboration",
    "Virtual Collaboration",
    "Remote Work",
    "Team Leadership",
    "People Management",
    "Team Building",
    "Mentoring",
    "Coaching",
    "Feedback Delivery",
    "Conflict Resolution",
    "Problem Solving",
    "Critical Thinking",
    "Analytical Thinking",
    "Strategic Thinking",
    "Decision Making",
    "Time Management",
    "Prioritization",
    "Multitasking",
    "Adaptability",
    "Flexibility",
    "Emotional Intelligence",
    "Empathy",
    "Cultural Awareness",
    "Growth Mindset",
  ],

  // ========================
  // DESIGN & UX SKILLS
  // ========================
  "Design & UX": [
    "Figma",
    "Adobe XD",
    "Sketch",
    "InVision",
    "Zeplin",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe After Effects",
    "Adobe Premiere",
    "UI Design",
    "UX Design",
    "Wireframing",
    "Prototyping",
    "User Research",
    "Usability Testing",
    "Design Systems",
    "Component Libraries",
    "Interaction Design",
    "Visual Design",
    "Information Architecture",
    "Design Thinking",
    "Accessibility Design",
    "Mobile Design",
    "Responsive Design",
    "Motion Design",
    "Animation",
    "Graphic Design",
    "Brand Design",
    "Logo Design",
    "Print Design",
    "Packaging Design",
  ],

  // ========================
  // TOOLS & PRODUCTIVITY
  // ========================
  "Tools & Productivity": [
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "VS Code",
    "IntelliJ IDEA",
    "Slack",
    "Microsoft Teams",
    "Zoom",
    "Google Meet",
    "Notion",
    "Obsidian",
    "Microsoft Office Suite",
    "Microsoft Word",
    "Microsoft Excel",
    "Microsoft PowerPoint",
    "Microsoft Outlook",
    "Google Workspace",
    "Google Docs",
    "Google Sheets",
    "Google Slides",
    "Miro",
    "Lucidchart",
    "Draw.io",
    "Canva",
    "Loom",
    "Calendly",
    "DocuSign",
    "SharePoint",
    "OneDrive",
    "Dropbox",
    "Box",
  ],

  // ========================
  // DOMAIN EXPERTISE
  // ========================
  "Domain Expertise": [
    "E-commerce",
    "FinTech",
    "HealthTech",
    "EdTech",
    "SaaS",
    "B2B",
    "B2C",
    "D2C",
    "Enterprise Software",
    "Payments & Billing",
    "Banking & Finance",
    "Insurance",
    "Lending",
    "Wealth Management",
    "Capital Markets",
    "Retail",
    "FMCG",
    "Consumer Goods",
    "Logistics & Supply Chain",
    "Real Estate",
    "PropTech",
    "Travel & Hospitality",
    "Gaming",
    "Media & Entertainment",
    "OTT",
    "Advertising & AdTech",
    "MarTech",
    "HR Tech",
    "LegalTech",
    "AgriTech",
    "CleanTech",
    "Telecommunications",
    "Manufacturing",
    "Automotive",
    "EV",
    "Energy & Utilities",
    "Oil & Gas",
    "Pharma",
    "Healthcare",
    "Medical Devices",
    "Biotech",
    "Government & Public Sector",
    "Non-profit",
    "NGO",
    "Social Impact",
  ],
};

// Flatten skills for search
export const ALL_SKILLS = Object.entries(SKILLS).flatMap(([category, skills]) =>
  skills.map(skill => ({ value: skill, label: skill, category }))
);

// Get skills count
export const SKILLS_COUNT = ALL_SKILLS.length;

// ============================================================================
// LOCATIONS DATABASE
// ============================================================================

export const LOCATIONS = {
  "India - Metro Cities": [
    "Bangalore",
    "Mumbai",
    "Delhi NCR",
    "Hyderabad",
    "Chennai",
    "Pune",
    "Kolkata",
    "Ahmedabad",
    "Noida",
    "Gurugram",
  ],
  "India - Tier 2 Cities": [
    "Jaipur",
    "Lucknow",
    "Chandigarh",
    "Indore",
    "Bhopal",
    "Kochi",
    "Coimbatore",
    "Nagpur",
    "Vadodara",
    "Surat",
    "Mysore",
    "Trivandrum",
    "Vizag",
    "Mangalore",
    "Nashik",
    "Patna",
    "Ranchi",
    "Bhubaneswar",
    "Raipur",
    "Dehradun",
  ],
  "India - States": [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Delhi",
    "Jammu & Kashmir",
    "Ladakh",
  ],
  "Global - North America": [
    "United States",
    "USA - California",
    "USA - New York",
    "USA - Texas",
    "USA - Washington",
    "USA - Massachusetts",
    "USA - Illinois",
    "USA - Florida",
    "USA - Georgia",
    "USA - Colorado",
    "Canada",
    "Canada - Ontario",
    "Canada - British Columbia",
    "Canada - Quebec",
    "Canada - Alberta",
  ],
  "Global - Europe": [
    "United Kingdom",
    "UK - London",
    "UK - Manchester",
    "Germany",
    "Germany - Berlin",
    "Germany - Munich",
    "Germany - Frankfurt",
    "Netherlands",
    "Netherlands - Amsterdam",
    "Ireland",
    "Ireland - Dublin",
    "France",
    "France - Paris",
    "Switzerland",
    "Switzerland - Zurich",
    "Sweden",
    "Sweden - Stockholm",
    "Poland",
    "Poland - Warsaw",
    "Spain",
    "Spain - Barcelona",
    "Spain - Madrid",
    "Italy",
    "Portugal",
    "Denmark",
    "Norway",
    "Finland",
    "Belgium",
    "Austria",
    "Czech Republic",
  ],
  "Global - Middle East": [
    "United Arab Emirates",
    "UAE - Dubai",
    "UAE - Abu Dhabi",
    "Saudi Arabia",
    "Saudi Arabia - Riyadh",
    "Saudi Arabia - Jeddah",
    "Qatar",
    "Qatar - Doha",
    "Bahrain",
    "Kuwait",
    "Oman",
    "Israel",
    "Israel - Tel Aviv",
  ],
  "Global - Asia Pacific": [
    "Singapore",
    "Australia",
    "Australia - Sydney",
    "Australia - Melbourne",
    "Australia - Brisbane",
    "Japan",
    "Japan - Tokyo",
    "Hong Kong",
    "Malaysia",
    "Malaysia - Kuala Lumpur",
    "Indonesia",
    "Indonesia - Jakarta",
    "Philippines",
    "Philippines - Manila",
    "Vietnam",
    "Vietnam - Ho Chi Minh City",
    "Thailand",
    "Thailand - Bangkok",
    "South Korea",
    "South Korea - Seoul",
    "Taiwan",
    "New Zealand",
  ],
  "Remote": [
    "Remote - India Only",
    "Remote - Global",
    "Remote - US Timezone",
    "Remote - EU Timezone",
    "Remote - APAC Timezone",
    "Hybrid - Flexible",
    "Hybrid - 2-3 Days Office",
    "Work From Anywhere",
  ],
};

// Flatten for dropdown with regions
export const ALL_LOCATIONS = Object.entries(LOCATIONS).flatMap(([region, locations]) =>
  locations.map(loc => ({ value: loc, label: loc, region }))
);

// Experience years options (0-40)
export const EXPERIENCE_YEARS = [
  { value: "0", label: "Fresher (0 years)" },
  { value: "1", label: "1 year" },
  { value: "2", label: "2 years" },
  { value: "3", label: "3 years" },
  { value: "4", label: "4 years" },
  { value: "5", label: "5 years" },
  { value: "6", label: "6 years" },
  { value: "7", label: "7 years" },
  { value: "8", label: "8 years" },
  { value: "9", label: "9 years" },
  { value: "10", label: "10 years" },
  { value: "11", label: "11 years" },
  { value: "12", label: "12 years" },
  { value: "13", label: "13 years" },
  { value: "14", label: "14 years" },
  { value: "15", label: "15 years" },
  { value: "16", label: "16 years" },
  { value: "17", label: "17 years" },
  { value: "18", label: "18 years" },
  { value: "19", label: "19 years" },
  { value: "20", label: "20 years" },
  { value: "21", label: "21-25 years" },
  { value: "26", label: "26-30 years" },
  { value: "31", label: "31-35 years" },
  { value: "36", label: "36-40 years" },
];

// Experience months options
export const EXPERIENCE_MONTHS = [
  { value: "0", label: "0 months" },
  { value: "1", label: "1 month" },
  { value: "2", label: "2 months" },
  { value: "3", label: "3 months" },
  { value: "4", label: "4 months" },
  { value: "5", label: "5 months" },
  { value: "6", label: "6 months" },
  { value: "7", label: "7 months" },
  { value: "8", label: "8 months" },
  { value: "9", label: "9 months" },
  { value: "10", label: "10 months" },
  { value: "11", label: "11 months" },
];

// Roles: minimum 3, maximum 10
export const MIN_ROLES = 3;
export const MAX_ROLES = 10;

// Max skills for auto-selection from resume
export const MAX_SKILLS_AUTO = 10;

// Max skills before warning
export const MAX_SKILLS_WARNING = 20;
