// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sutjrevtlmqpnrqfgzap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1dGpyZXZ0bG1xcG5ycWZnemFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5OTY1NzAsImV4cCI6MjA2ODU3MjU3MH0.U6vZgOiR7LUmBoWp39_XRNq8S5CwyFB5u4Lj3y6XQW8";

// Singleton pattern to prevent multiple Supabase client instances
let supabaseClient: SupabaseClient<Database> | null = null;

export const getSupabaseClient = (): SupabaseClient<Database> => {
  if (!supabaseClient) {
    supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: window.localStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        flowType: 'pkce',
        debug: false
      }
    });
  }
  return supabaseClient;
};

// Export singleton instance
export const supabase = getSupabaseClient();